site_name: OpenTenBase Documentation
repo_url: https://github.com/OpenTenBase/docs
repo_name: OpenTenBase/docs
edit_uri: edit/main/docs/

theme:
  name: material

  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github

  markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true 
    - tables
    - attr_list
    - md_in_html

nav:
  - 首页: index.md
  - 用户指南:
    - 快速入门: guide/quickstart.md
    - 基本使用: guide/use.md
  - 版本说明:
    - v2.5.0: release/v2.5.0.md
    - v2.4.0: release/v2.4.0.md
  - 常见问题: faq.md
  - 参与贡献:
    - 如何贡献: contribution/how-to.md
    - 文档库格式手册: contribution/docs-format-guide.md
  - 下载: https://github.com/OpenTenBase/OpenTenBase/tags


plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          default: true
          name: 中文
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
              首页: Home
              快速入门: Quick Start
              基本使用: Usage
              用户指南: Guide
              基础配置: Configuation
              版本说明: Releases
              常见问题: FAQ
              参与贡献: Contributing
              如何贡献: How to contribute
              文档库格式手册: Documentation format guide
              下载: Download